version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: changuito
      MONGO_INITDB_ROOT_PASSWORD: smart

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: changuito
      ME_CONFIG_MONGODB_ADMINPASSWORD: smart
      ME_CONFIG_MONGODB_URL: mongodb://changuito:smart@mongo:27017/
